const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={q:'',location:'',category:'all',offset:0,loading:false,hasMore:true,jobs:[]};
const categoryNames={all:'Vård & omsorg',doctor:'Läkarjobb','doctor-training':'ST, BT, AT & underläkarjobb',nurse:'Sjuksköterskejobb',assistant:'Undersköterskejobb',elderly:'Äldreomsorg & hemtjänst',lss:'LSS & omsorg',dental:'Tandvård',rehab:'Rehab',mental:'Psykolog & kurator'};
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function relativeDate(v){if(!v)return'';const d=new Date(v),days=Math.floor((Date.now()-d)/86400000);if(days<=0)return'Idag';if(days===1)return'Igår';if(days<7)return`${days} dagar sedan`;return d.toLocaleDateString('sv-SE',{day:'numeric',month:'short'})}
function deadline(v){if(!v)return null;const d=new Date(v),days=Math.ceil((d-Date.now())/86400000);return {label:days<0?'Ansökan stängd':days===0?'Sista ansökningsdag idag':days===1?'1 dag kvar':`${days} dagar kvar`,soon:days>=0&&days<=5}}
function isNew(v){return v && (Date.now()-new Date(v).getTime())<72*3600000}
function params(){const p=new URLSearchParams({category:state.category,offset:String(state.offset),limit:'40'});if(state.q)p.set('q',state.q);if(state.location)p.set('location',state.location);return p}
function updateUrl(){const p=new URLSearchParams();if(state.q)p.set('q',state.q);if(state.location)p.set('location',state.location);if(state.category!=='all')p.set('category',state.category);history.replaceState(null,'',p.toString()?`?${p}`:'/')}
function setSkeletons(){const box=$('#jobList');box.innerHTML='';for(let i=0;i<5;i++)box.append($('#skeletonTemplate').content.cloneNode(true))}
function card(j){const dl=deadline(j.deadline);return `<article class="job-card"><div class="job-card-top"><div><div class="job-source">${isNew(j.publishedAt)?'<span class="fresh-dot"></span>':''}${esc(j.source||'Originalannons')} · ${esc(relativeDate(j.publishedAt))}</div><h3><a href="${esc(j.url)}" target="_blank" rel="noopener">${esc(j.title)}</a></h3><div class="job-employer">${esc(j.employer)}</div></div>${isNew(j.publishedAt)?'<span class="new-pill">Ny</span>':''}</div><div class="job-meta">${j.location||j.region?`<span>⌖ ${esc([j.location,j.region].filter(Boolean).join(', '))}</span>`:''}${j.occupation?`<span>◦ ${esc(j.occupation)}</span>`:''}${j.vacancies?`<span>◦ ${j.vacancies} tjänst${j.vacancies>1?'er':''}</span>`:''}${dl?`<span class="${dl.soon?'deadline-soon':''}">◦ ${esc(dl.label)}</span>`:''}</div>${j.brief?`<p class="job-brief">${esc(j.brief)}</p>`:''}${j.tags?.length?`<div class="job-tags">${j.tags.map(t=>`<span class="job-tag ${/ST|BT|AT|Underläkare/.test(t)?'hot':''}">${esc(t)}</span>`).join('')}</div>`:''}</article>`}
function currentLabel(){const parts=[];if(state.q)parts.push(`“${state.q}”`);else parts.push(categoryNames[state.category]||'Vård & omsorg');if(state.location)parts.push(state.location);else parts.push('hela Sverige');return parts.join(' · ')}
async function load(reset=true){if(state.loading)return;state.loading=true;if(reset){state.offset=0;state.jobs=[];setSkeletons()}$('#loadMore').hidden=true;$('#resultTitle').textContent=currentLabel();$('#resultMeta').textContent='Hämtar aktuella jobb…';updateUrl();updateRss();syncFilter();try{const r=await fetch(`/api/jobs?${params()}`);if(!r.ok)throw new Error();const data=await r.json();state.jobs=reset?data.jobs:[...state.jobs,...data.jobs.filter(x=>!state.jobs.some(y=>y.id===x.id))];state.offset=data.nextOffset;state.hasMore=data.jobs.length>=35;$('#jobList').innerHTML=state.jobs.length?state.jobs.map(card).join(''):`<div class="empty-state"><h3>Inga jobb hittades</h3><p>Prova ett bredare sökord eller ta bort platsfiltret.</p></div>`;const count=data.total?`${data.total.toLocaleString('sv-SE')} träffar i källan`:`${state.jobs.length} aktuella träffar visade`;$('#resultMeta').textContent=`${count}${data.partial?' · en källa svarade inte':''} · uppdateras automatiskt`;$('#loadMore').hidden=!state.hasMore;markVisit();}catch(e){$('#jobList').innerHTML='<div class="error-box"><strong>Kunde inte hämta jobben just nu.</strong><br>Försök igen om en liten stund.</div>';$('#resultMeta').textContent='Tillfälligt fel vid hämtning';}finally{state.loading=false;renderSaved()}}
function syncFilter(){$$('.filter-chip').forEach(b=>b.classList.toggle('active',b.dataset.category===state.category))}
function updateRss(){const p=new URLSearchParams({category:state.category});if(state.q)p.set('q',state.q);if(state.location)p.set('location',state.location);$('#rssLink').href=`/api/feed?${p}`}
function saved(){try{return JSON.parse(localStorage.getItem('vardanstallning.saved')||'[]')}catch{return[]}}
function keyFor(s=state){return JSON.stringify([s.q||'',s.location||'',s.category||'all'])}
function saveCurrent(){let arr=saved(),key=keyFor();const i=arr.findIndex(x=>x.key===key);if(i>=0)arr.splice(i,1);else arr.unshift({key,q:state.q,location:state.location,category:state.category,label:currentLabel(),savedAt:new Date().toISOString(),lastSeen:new Date().toISOString()});localStorage.setItem('vardanstallning.saved',JSON.stringify(arr.slice(0,12)));renderSaved()}
function renderSaved(){const arr=saved(),key=keyFor();$('#savedCount').textContent=arr.length;$('#watchButton').classList.toggle('watching',arr.some(x=>x.key===key));$('#watchButton').textContent=arr.some(x=>x.key===key)?'★ Bevakad':'☆ Bevaka sökningen';$('#savedSearches').innerHTML=arr.length?arr.map((s,i)=>`<div class="saved-item" data-saved-index="${i}"><div class="saved-item-row"><strong>${esc(s.label)}</strong><button class="remove-saved" data-remove-index="${i}">Ta bort</button></div><span>Sparad ${new Date(s.savedAt).toLocaleDateString('sv-SE')}</span></div>`).join(''):'<div class="saved-empty">Du har inga bevakningar ännu. Gör en sökning och välj <strong>Bevaka sökningen</strong>.</div>'}
function markVisit(){let arr=saved(),key=keyFor(),changed=false;arr=arr.map(x=>{if(x.key===key){changed=true;return {...x,lastSeen:new Date().toISOString()}}return x});if(changed)localStorage.setItem('vardanstallning.saved',JSON.stringify(arr))}
function applySaved(s){state.q=s.q||'';state.location=s.location||'';state.category=s.category||'all';$('#query').value=state.q;$('#location').value=state.location;$('#savedPanel').classList.remove('open');load(true)}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();state.q=$('#query').value.trim();state.location=$('#location').value.trim();state.category='all';load(true)});
$$('.filter-chip').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.category;state.q='';$('#query').value='';load(true)}));
$$('.quick-chip').forEach(b=>b.addEventListener('click',()=>{state.q=b.dataset.query||'';state.category=b.dataset.category||'all';$('#query').value=state.q;load(true);document.querySelector('.content-shell').scrollIntoView({behavior:'smooth'})}));
$('#loadMore').addEventListener('click',()=>load(false));$('#watchButton').addEventListener('click',saveCurrent);$('#savedToggle').addEventListener('click',()=>$('#savedPanel').classList.toggle('open'));$('#closeSaved').addEventListener('click',()=>$('#savedPanel').classList.remove('open'));
$('#savedSearches').addEventListener('click',e=>{const rm=e.target.closest('[data-remove-index]');if(rm){e.stopPropagation();const arr=saved();arr.splice(Number(rm.dataset.removeIndex),1);localStorage.setItem('vardanstallning.saved',JSON.stringify(arr));renderSaved();return}const item=e.target.closest('[data-saved-index]');if(item)applySaved(saved()[Number(item.dataset.savedIndex)])});
const initial=new URLSearchParams(location.search);state.q=initial.get('q')||'';state.location=initial.get('location')||'';state.category=initial.get('category')||'all';$('#query').value=state.q;$('#location').value=state.location;renderSaved();load(true);
