const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={q:'',location:'',category:'all',offset:0,loading:false,hasMore:true,jobs:[],freshOnly:false,sort:'newest'};
const categoryNames={all:'Alla vård- och omsorgsjobb',doctor:'Läkarjobb',st:'ST-läkarjobb',bt:'BT-läkarjobb',at:'AT-läkarjobb',underdoctor:'Underläkarjobb & vikariat',nurse:'Sjuksköterskejobb',assistant:'Undersköterskejobb',midwife:'Barnmorskejobb',ambulance:'Ambulanssjukvård',elderly:'Äldreomsorg & hemtjänst',lss:'LSS & funktionsstöd',social:'Socialt arbete',careworker:'Vårdbiträden & skötare',rehab:'Hälsa & rehab',mental:'Psykolog & kurator',dental:'Tandvård',pharmacy:'Apotek',lifescience:'Life Science',research:'Forskning',veterinary:'Djursjukvård',radiology:'Radiologi',biomed:'Laboratorium / BMA',admin:'Vårdadministration',leadership:'Vårdledning',other:'Övriga vårdjobb'};
const categoryPaths={doctor:'/jobb/lakare',st:'/jobb/st-lakare',bt:'/jobb/bt-lakare',at:'/jobb/at-lakare',underdoctor:'/jobb/underlakare',nurse:'/jobb/sjukskoterska',assistant:'/jobb/underskoterska',elderly:'/jobb/aldreomsorg-hemtjanst',lss:'/jobb/lss-omsorg',dental:'/jobb/tandvard',rehab:'/jobb/rehab',social:'/jobb/socialt-arbete',pharmacy:'/jobb/apotek',veterinary:'/jobb/djursjukvard',lifescience:'/jobb/life-science'};
const pathCategories=Object.fromEntries(Object.entries(categoryPaths).map(([k,v])=>[v,k]));
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function relativeDate(v){if(!v)return'';const d=new Date(v),days=Math.floor((Date.now()-d)/86400000);if(days<=0)return'Idag';if(days===1)return'Igår';if(days<7)return`${days} dagar sedan`;return d.toLocaleDateString('sv-SE',{day:'numeric',month:'short'})}
function deadline(v){if(!v)return null;const d=new Date(v),days=Math.ceil((d-Date.now())/86400000);return{days,label:days<0?'Ansökan stängd':days===0?'Sista ansökningsdag idag':days===1?'1 dag kvar':`${days} dagar kvar`,soon:days>=0&&days<=5}}
function isFresh(v){return v&&(Date.now()-new Date(v).getTime())<72*3600000}
function params(){const p=new URLSearchParams({category:state.category,offset:String(state.offset),limit:'40'});if(state.q)p.set('q',state.q);if(state.location)p.set('location',state.location);return p}
function updateUrl(){const p=new URLSearchParams();if(state.q)p.set('q',state.q);if(state.location)p.set('location',state.location);if(state.q){if(state.category!=='all')p.set('category',state.category);history.replaceState(null,'',`/?${p}`);return}const base=categoryPaths[state.category]||'/';history.replaceState(null,'',p.toString()?`${base}?${p}`:base)}
function setSkeletons(){const box=$('#jobList');box.innerHTML='';for(let i=0;i<5;i++)box.append($('#skeletonTemplate').content.cloneNode(true))}
function card(j){const dl=deadline(j.deadline);return`<article class="job-card"><div class="job-card-top"><div><div class="job-source">${isFresh(j.publishedAt)?'<span class="fresh-dot"></span>':''}${esc(j.source||'Originalannons')} · ${esc(relativeDate(j.publishedAt))}</div><h3><a href="${esc(j.url)}" target="_blank" rel="noopener">${esc(j.title)}</a></h3><div class="job-employer">${esc(j.employer)}</div></div>${isFresh(j.publishedAt)?'<span class="new-pill">Ny</span>':''}</div><div class="job-meta">${j.location||j.region?`<span>⌖ ${esc([j.location,j.region].filter(Boolean).join(', '))}</span>`:''}${j.occupation?`<span>◦ ${esc(j.occupation)}</span>`:''}${j.vacancies?`<span>◦ ${j.vacancies} tjänst${j.vacancies>1?'er':''}</span>`:''}${dl?`<span class="${dl.soon?'deadline-soon':''}">◦ ${esc(dl.label)}</span>`:''}</div>${j.brief?`<p class="job-brief">${esc(j.brief)}</p>`:''}${j.tags?.length?`<div class="job-tags">${j.tags.map(t=>`<span class="job-tag ${/ST|BT|AT|Underläkare/.test(t)?'hot':''}">${esc(t)}</span>`).join('')}</div>`:''}</article>`}
function currentLabel(){const parts=[state.q?`“${state.q}”`:(categoryNames[state.category]||'Jobb')];parts.push(state.location||'hela Sverige');return parts.join(' · ')}
function sortedVisible(){let list=[...state.jobs];if(state.freshOnly)list=list.filter(x=>isFresh(x.publishedAt));if(state.sort==='deadline')list.sort((a,b)=>new Date(a.deadline||'2999-12-31')-new Date(b.deadline||'2999-12-31'));else list.sort((a,b)=>new Date(b.publishedAt||0)-new Date(a.publishedAt||0));return list}
function renderJobs(){const list=sortedVisible();$('#jobList').innerHTML=list.length?list.map(card).join(''):`<div class="empty-state"><h3>Inga jobb hittades</h3><p>${state.freshOnly?'Inga träffar från de senaste tre dygnen.':'Prova ett bredare sökord eller ta bort platsfiltret.'}</p></div>`}
function saved(){try{return JSON.parse(localStorage.getItem('vardanstallning.saved')||'[]')}catch{return[]}}
function keyFor(s=state){return JSON.stringify([s.q||'',s.location||'',s.category||'all'])}
function lastSeen(){return saved().find(x=>x.key===keyFor())?.lastSeen||null}
function showNewSince(previousSeen){const el=$('#newSince');if(!previousSeen){el.hidden=true;return}const n=state.jobs.filter(x=>x.publishedAt&&new Date(x.publishedAt)>new Date(previousSeen)).length;if(!n){el.hidden=true;return}el.hidden=false;el.innerHTML=`<strong>${n} nya ${n===1?'annons':'annonser'} sedan du kollade senast.</strong>`}
function updateMeta(data){const fresh=state.jobs.filter(x=>isFresh(x.publishedAt)).length;const bits=[`${state.jobs.length} relevanta träffar visade`];if(fresh)bits.push(`${fresh} nya senaste 3 dygnen`);bits.push('flera källor');if(data.partial)bits.push('en källa svarade inte');$('#resultMeta').textContent=bits.join(' · ')}
async function load(reset=true){if(state.loading)return;state.loading=true;const previousSeen=reset?lastSeen():null;if(reset){state.offset=0;state.jobs=[];setSkeletons()}$('#loadMore').hidden=true;$('#resultTitle').textContent=currentLabel();$('#resultMeta').textContent='Hämtar aktuella jobb…';document.title=`${currentLabel()} | Vårdanställning`;updateUrl();updateRss();syncFilter();try{const r=await fetch(`/api/jobs?${params()}`);if(!r.ok)throw new Error();const data=await r.json();state.jobs=reset?data.jobs:[...state.jobs,...data.jobs.filter(x=>!state.jobs.some(y=>y.id===x.id||y.url===x.url))];state.offset=data.nextOffset;state.hasMore=data.jobs.length>=35;renderJobs();updateMeta(data);if(reset)showNewSince(previousSeen);$('#loadMore').hidden=!state.hasMore;markVisit()}catch(e){$('#jobList').innerHTML='<div class="error-box"><strong>Kunde inte hämta jobben just nu.</strong><br>Försök igen senare.</div>';$('#resultMeta').textContent='Tillfälligt fel vid hämtning'}finally{state.loading=false;renderSaved()}}
function syncFilter(){$$('.filter-chip').forEach(b=>b.classList.toggle('active',b.dataset.category===state.category));$('#freshToggle').classList.toggle('active',state.freshOnly)}
function updateRss(){const p=new URLSearchParams({category:state.category});if(state.q)p.set('q',state.q);if(state.location)p.set('location',state.location);$('#rssLink').href=`/api/feed?${p}`}
function saveCurrent(){let arr=saved(),key=keyFor(),i=arr.findIndex(x=>x.key===key);if(i>=0){arr.splice(i,1);toast('Sparad bevakning togs bort')}else{arr.unshift({key,q:state.q,location:state.location,category:state.category,label:currentLabel(),savedAt:new Date().toISOString(),lastSeen:new Date().toISOString()});toast('Sökningen sparad på den här enheten')}localStorage.setItem('vardanstallning.saved',JSON.stringify(arr.slice(0,20)));renderSaved()}
function renderSaved(){const arr=saved(),key=keyFor();$('#savedCount').textContent=arr.length;const watching=arr.some(x=>x.key===key);$('#watchButton').classList.toggle('watching',watching);$('#watchButton').textContent=watching?'★ Sparad':'☆ Spara';$('#savedSearches').innerHTML=arr.length?arr.map((s,i)=>`<div class="saved-item" data-saved-index="${i}"><div class="saved-item-row"><strong>${esc(s.label)}</strong><button class="remove-saved" data-remove-index="${i}">Ta bort</button></div><span>Senast öppnad ${new Date(s.lastSeen||s.savedAt).toLocaleDateString('sv-SE')}</span></div>`).join(''):'<div class="saved-empty">Du har inga lokalt sparade sökningar ännu.</div>'}
function markVisit(){let arr=saved(),key=keyFor(),changed=false;arr=arr.map(x=>{if(x.key===key){changed=true;return{...x,lastSeen:new Date().toISOString()}}return x});if(changed)localStorage.setItem('vardanstallning.saved',JSON.stringify(arr))}
function applySaved(s){state.q=s.q||'';state.location=s.location||'';state.category=s.category||'all';$('#query').value=state.q;$('#location').value=state.location;$('#savedPanel').classList.remove('open');load(true)}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2400)}
async function shareSearch(){try{if(navigator.share)await navigator.share({title:currentLabel(),url:location.href});else{await navigator.clipboard.writeText(location.href);toast('Länken kopierad')}}catch(e){}}
function selectCategory(category){state.category=category;state.q='';$('#query').value='';load(true);document.querySelector('.content-shell').scrollIntoView({behavior:'smooth'})}
function populateAlertCategory(){const select=$('#alertCategory');select.innerHTML=Object.entries(categoryNames).map(([v,l])=>`<option value="${v}">${esc(l)}</option>`).join('')}
function openAlert(){populateAlertCategory();$('#alertQuery').value=state.q;$('#alertLocation').value=state.location;$('#alertCategory').value=state.category;$('#alertStatus').textContent='';$('#alertModal').hidden=false;document.body.classList.add('modal-open');setTimeout(()=>$('#alertEmail').focus(),50)}
function closeAlert(){$('#alertModal').hidden=true;document.body.classList.remove('modal-open')}
async function submitAlert(e){e.preventDefault();const btn=e.currentTarget.querySelector('button[type=submit]'),status=$('#alertStatus');btn.disabled=true;status.textContent='Skapar bevakning…';try{const r=await fetch('/api/alerts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#alertEmail').value,query:$('#alertQuery').value,location:$('#alertLocation').value,category:$('#alertCategory').value,frequency:$('#alertFrequency').value})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Kunde inte skapa bevakning');if(data.verificationSent){status.textContent='✓ Klart! Kolla din inkorg och bekräfta bevakningen.';status.className='form-status success'}else{status.textContent='Bevakningen är sparad, men e-postleveransen håller på att aktiveras.';status.className='form-status warning'}}catch(err){status.textContent='Kunde inte aktivera e-postbevakningen just nu.';status.className='form-status error'}finally{btn.disabled=false}}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();state.q=$('#query').value.trim();state.location=$('#location').value.trim();state.category='all';load(true)});
$$('.filter-chip,.quick-chip').forEach(b=>b.addEventListener('click',()=>selectCategory(b.dataset.category||'all')));
$$('.profession-grid button').forEach(b=>b.addEventListener('click',()=>selectCategory(b.dataset.category)));
$('#freshToggle').addEventListener('click',()=>{state.freshOnly=!state.freshOnly;syncFilter();renderJobs()});$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;renderJobs()});$('#loadMore').addEventListener('click',()=>load(false));$('#watchButton').addEventListener('click',saveCurrent);$('#shareButton').addEventListener('click',shareSearch);$('#savedToggle').addEventListener('click',()=>$('#savedPanel').classList.toggle('open'));$('#closeSaved').addEventListener('click',()=>$('#savedPanel').classList.remove('open'));$('#emailAlertButton').addEventListener('click',openAlert);$('#heroAlertButton').addEventListener('click',openAlert);$$('[data-close-alert]').forEach(x=>x.addEventListener('click',closeAlert));$('#alertForm').addEventListener('submit',submitAlert);
$('#savedSearches').addEventListener('click',e=>{const rm=e.target.closest('[data-remove-index]');if(rm){e.stopPropagation();const arr=saved();arr.splice(Number(rm.dataset.removeIndex),1);localStorage.setItem('vardanstallning.saved',JSON.stringify(arr));renderSaved();return}const item=e.target.closest('[data-saved-index]');if(item)applySaved(saved()[Number(item.dataset.savedIndex)])});
const initial=new URLSearchParams(location.search);state.q=initial.get('q')||'';state.location=initial.get('location')||'';state.category=initial.get('category')||pathCategories[location.pathname.replace(/\/$/,'')]||'all';$('#query').value=state.q;$('#location').value=state.location;renderSaved();load(true);
